---
- name: Format NameNode
  command: "sudo -u hadoop {{ hadoop_home }}/bin/hdfs namenode -format -force"
  args:
    creates: "{{ dfs_namenode_name_dir }}/current/VERSION"
  when: inventory_hostname == 'nn1' and format_nn | default(false)
  run_once: true

- name: Start the NameNode
  systemd:
    name: hadoop-namenode
    state: started
  when: inventory_hostname == 'nn1' and format_nn | default(false)
