all:
  children:
    hadoop_ha:
      children:
        namenodes:
          hosts:
            nn1:
              ansible_host: 10.0.0.111
            nn2:
              ansible_host: 10.0.0.112
        datanodes:
          hosts:
            dn1:
              ansible_host: 10.0.0.113
            dn2:
              ansible_host: 10.0.0.114
        journalnodes:
          hosts:
            nn1:
              ansible_host: 10.0.0.111
            dn1:
              ansible_host: 10.0.0.113
            dn2:
              ansible_host: 10.0.0.114
        zookeepers:
          hosts:
            nn1:
              ansible_host: 10.0.0.111
              zk_id: 1
            nn2:
              ansible_host: 10.0.0.112
              zk_id: 2
            dn1:
              ansible_host: 10.0.0.113
              zk_id: 3
    clients:
      hosts:
        client:
          ansible_host: 10.0.0.115
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: /home/abid/.vagrant.d/insecure_private_key
