all:
  children:
    hadoop_ha:
      children:
        namenodes:
          hosts:
            nn1:
              ansible_host: 192.168.174.111
            nn2:
              ansible_host: 192.168.174.112
        datanodes:
          hosts:
            dn1:
              ansible_host: 192.168.174.113
            dn2:
              ansible_host: 192.168.174.114
        journalnodes:
          hosts:
            dn1:
            dn2:
            nn1:
        zookeepers:
          hosts:
            nn1:
              zk_id: 1
            nn2:
              zk_id: 2
            dn1:
              zk_id: 3
    clients:
      hosts:
        client:
          ansible_host: 192.168.174.115
    version_compare:
      hosts:
        rocky10:
          ansible_host: 192.168.174.116
  vars:
    ansible_user: root
