require "yaml"

GLOBAL_VARS_FILE = File.expand_path("../inventory/group_vars/all.yml", __dir__)
GLOBAL_VARS = YAML.load_file(GLOBAL_VARS_FILE)
INVENTORY_FILE = File.expand_path("../inventory/hosts.yml", __dir__)
VAGRANT_SSH_PRIVATE_KEY = File.expand_path("~/.vagrant.d/insecure_private_key")

# VM, network, and HA group settings are maintained in inventory/group_vars/all.yml.
VAGRANT_BOX = GLOBAL_VARS.fetch("vagrant_box")
VAGRANT_BOX_VERSION = GLOBAL_VARS["vagrant_box_version"]
VM_NAME_PREFIX = GLOBAL_VARS.fetch("vagrant_vm_name_prefix")
VM_MEMORY_MB = GLOBAL_VARS.fetch("vagrant_vm_memory_mb")
VM_CPUS = GLOBAL_VARS.fetch("vagrant_vm_cpus")
HOST_ADDRESSES = GLOBAL_VARS.fetch("hadoop_host_addresses")

VM_SPECS = GLOBAL_VARS.fetch("vagrant_vm_specs").map do |spec|
  {
    name: spec.fetch("name"),
    groups: spec.fetch("groups"),
    zk_id: spec["zk_id"],
    ip: HOST_ADDRESSES.fetch(spec.fetch("name")),
    memory: spec.fetch("memory", VM_MEMORY_MB),
    cpus: spec.fetch("cpus", VM_CPUS)
  }
end

def render_inventory_hosts(specs, group, indentation, include_zk_id: false)
  specs
    .select { |spec| spec[:groups].include?(group) }
    .map do |spec|
      entry = "#{indentation}#{spec[:name]}:\n#{indentation}  ansible_host: #{spec[:ip]}"
      entry += "\n#{indentation}  zk_id: #{spec[:zk_id]}" if include_zk_id && spec[:zk_id]
      entry
    end
    .join("\n")
end

namenode_hosts = render_inventory_hosts(VM_SPECS, "namenodes", "            ")
datanode_hosts = render_inventory_hosts(VM_SPECS, "datanodes", "            ")
journalnode_hosts = render_inventory_hosts(VM_SPECS, "journalnodes", "            ")
zookeeper_hosts = render_inventory_hosts(VM_SPECS, "zookeepers", "            ", include_zk_id: true)
client_hosts = render_inventory_hosts(VM_SPECS, "clients", "        ")

File.write(INVENTORY_FILE, <<~YAML)
  all:
    children:
      hadoop_ha:
        children:
          namenodes:
            hosts:
  #{namenode_hosts}
          datanodes:
            hosts:
  #{datanode_hosts}
          journalnodes:
            hosts:
  #{journalnode_hosts}
          zookeepers:
            hosts:
  #{zookeeper_hosts}
      clients:
        hosts:
  #{client_hosts}
    vars:
      ansible_user: root
      ansible_ssh_private_key_file: #{VAGRANT_SSH_PRIVATE_KEY}
YAML

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.box_version = VAGRANT_BOX_VERSION unless VAGRANT_BOX_VERSION.nil?
  config.ssh.insert_key = false

  VM_SPECS.each do |spec|
    config.vm.define spec[:name] do |machine|
      machine.vm.hostname = spec[:name]
      machine.vm.network "private_network", ip: spec[:ip]
      machine.vm.synced_folder "..", "/vagrant"

      machine.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name = "#{VM_NAME_PREFIX}-#{spec[:name]}"
        virtualbox.memory = spec[:memory]
        virtualbox.cpus = spec[:cpus]
        virtualbox.gui = false
      end

      machine.vm.provision "shell", privileged: true, inline: <<-SHELL
        set -eu
        install -d -m 700 /root/.ssh
        touch /root/.ssh/authorized_keys
        cat /home/vagrant/.ssh/authorized_keys >> /root/.ssh/authorized_keys
        sort -u /root/.ssh/authorized_keys -o /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/authorized_keys
        if grep -q '^#\?PermitRootLogin' /etc/ssh/sshd_config; then
          sed -ri 's/^#?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
        else
          echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
        fi
        systemctl restart ssh || systemctl restart sshd
      SHELL
    end
  end
end
