# BEGIN VAGRANT GENERATED HOST ADDRESSES
hadoop_host_addresses:
  nn1: "10.0.0.111"
  dn1: "10.0.0.113"
  dn2: "10.0.0.114"
# END VAGRANT GENERATED HOST ADDRESSES

ansible_user: root
java_home: "/usr/lib/jvm/java-11-openjdk-amd64"

hadoop_version: "3.3.6"
hadoop_home: "/opt/hadoop"
hadoop_conf_dir: "{{ hadoop_home }}/etc/hadoop"

fs_default: "hdfs://nn1:8020"
dfs_namenode_rpc_address: "nn1:8020"
dfs_namenode_http_address: "nn1:9870"
dfs_replication: 2
dfs_namenode_name_dir: "/opt/hadoop/data/namenode"
dfs_datanode_data_dir: "/opt/hadoop/data/datanode"

yarn_resourcemanager_hostname: "nn1"
yarn_resourcemanager_address: "nn1:8032"
yarn_resourcemanager_scheduler_address: "nn1:8030"
yarn_resourcemanager_resource_tracker_address: "nn1:8031"
yarn_resourcemanager_admin_address: "nn1:8033"
yarn_resourcemanager_webapp_address: "nn1:8088"
